openshift/dpu-operator

Dockerfile.rhel
Makefile
bindata/daemon/02.daemon_role.yaml
config/rbac/role.yaml
dpu-cni/pkgs/cniserver/cniserver.go
dpu-cni/pkgs/cniserver/cniserver_test.go
internal/controller/dpuoperatorconfig_controller.go

Some of the RBAC permissions were not properly set, which precluded the daemonset from being created on a fresh cluster.
In addition, also fix the version of a tool used in the Makefile to avoid randomly breaking builds.

Fix daemon deployment from operator

---

daemon/dpudaemon.go
daemon/hostdaemon.go
daemon/main.go
daemon/main_test.go
daemon/plugin/vendorplugin.go
dpu-cni/pkgs/cniserver/cniserver.go
dpu-cni/pkgs/cniserver/cniserver_test.go
dpu-cni/pkgs/sriov/sriov.go

This PR adds functionality to propagate a CNI add for a device that is added on the host down to the DPU which in turns forwards that to the vendor plugin on the DPU.

Add CniServer into HostDaemon

---

bundle/manifests/dpu-operator.clusterserviceversion.yaml
config/manager/manager.yaml
manifests/stable/dpu-operator.clusterserviceversion.yaml
manifests/stable/image-references

Also replace any image references in our CSVs with "pretend" OKD images from quay.io. Please note that Red Hat isn't building OKD images as of writing.
Following: https://art-docs.engineering.redhat.com/olm-bundles/#image-references-and-specrelatedimages

Add image references for ART Team

---

Dockerfile.rhel

We are already vendoring this project. No need to run "go mod download"
Also the ART team builds in an air-gaped environment. Thus we cannot download anything.

Remove go mod download from dockerfile

---

Dockerfile.CNI.rhel

The ART team has issues building with RHEL8. Thus we need to upgrade to RHEL9.

Change the builder to RHEL9

---

daemon/main.go

It is most likely that we will in the future include a command line argument for the CNI path since different cluster types will have different CNI locations.
For now remove the check for "writeable()" and simplify the code to just attempt to copy and make executable. Errors are logged and not act upon.
The writeable() code also had a bug where it would check for the file and not the directory.

Let errors occur when copying the DPU CNI

---

daemon/main.go

Due to: https://github.com/bn222/dpu-operator/blame/a1ff551f544c1705dfdb18cb67a093124640cfa9/daemon/main.go#L119
From commit: "35ebd23" Add SFC reconciler to daemon

Fix DPU CNI binary copy regression

---

Makefile

Ginkgo is more feature rich and gives more control on the ordering of the tests when there are external dependencies (e.g. single kind cluster)

Switch to ginkgo for testing

---

bundle/manifests/dpu-operator.clusterserviceversion.yaml
config/manager/manager.yaml
manifests/stable/dpu-operator.clusterserviceversion.yaml

We need to specify the seccompProfile. Without this, the replicaset fails to start via "make local-deploy"  with the following error:
Warning  FailedCreate  35s (x5 over 73s)  replicaset-controller  (combined from similar events): Error creating: pods "dpu-operator-controller-manager-5f95b6c647-bkf85" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "manager", "kube-rbac-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

Set seccompProfile in operator replicaset

---

bundle/manifests/dpu-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/dpuoperatorconfig_controller.go
manifests/stable/dpu-operator.clusterserviceversion.yaml

This is required when ensuring the daemon is running.
Without this role, we will hit the following error:
2024-07-08T19:55:23Z    ERROR   Reconciler error        {"controller":
"dpuoperatorconfig", "controllerGroup": "config.openshift.io",
"controllerKind": "DpuOperatorConfig", "DpuOperatorConfig":
{"name":"dpu-operator-config"}, "namespace": "", "name": "dpu-operato
r-config", "reconcileID": "8ff59f4b-9f68-4dc6-b859-8dfb59ec9acc",
"error": "failed to apply object
&{map[apiVersion:rbac.authorization.k8s.io/v1 kind:ClusterRole
metadata:map[name:dpu-daemon-cluster-role
ownerReferences:[map[apiVersion:config.openshift.io/v1 bloc
kOwnerDeletion:true controller:true kind:DpuOperatorConfig
name:dpu-operator-config uid:dfba8a8b-23f6-4848-8a96-85aac4a5b0d6]]] …

Fix clusterrole

---

config/manager/manager.yaml

When deploying the dpu daemon daemonset via make local-deploy the daemonset pods fail to come up due to the level of privlege required by the pods.
i.e.
securityContext.privileged=true
allowPrivilegeEscalation!=false
hostNetwork=true
hostPID=true
volumes "devicesock", "dpu-daemon-mount", "var-cni-dir", "opt-cni-dir", "host-run", "proc" use restricted volume type "hostPath" ! securityContext.capabilities.drop=["ALL"]
securityContext.seccompProfile.type!="RuntimeDefault" or "Localhost"
We can fix this by expanding the privileges of the dpu operator namespace to match what is required by the daemon

add required labels to dpu operator ns

---

internal/controller/dpuoperatorconfig_controller_test.go

Update test name to properly reflect what is being tested.
On my machine this test will fail due to the net-attach-def not yet existing. Increasing the timeout resolves this issue.

Fix typo in controller test name and increase t/o

---

Makefile
README.md
config/dev/kustomization.yaml
config/dev/local-images-template.yaml
tools/config.go
tools/go.mod

This allows to build locally without having to manually change a file. This PR adds a tool that will write a kustomize config with the right arguments defined in the Makefile.
Also, clean up the targets and docs.

Clean up local build targets

---

cmd/daemon/daemon.go
internal/platform/ipu.go
internal/platform/platform.go

We need to create a new instance of the PlatformInfo struct to ensure the NewIntelDetector is added.
Additionally, fix a small bug in determining a device is an Intel DPU. The Intel IPU pci Class/Vendor/Product should be:
Network controller Intel Corporation Infrastructure Data Path Function

Fix bug in DPU Platform Info

---

manifests/stable/dpu-operator.clusterserviceversion.yaml
manifests/stable/image-references

Fix incorrect image references in `release-4.18`
Please verify and follow up if other places need to be modified as well.

NO-JIRA: fix image references in 4.18

---

manifests/stable/dpu-operator.clusterserviceversion.yaml
manifests/stable/image-references

Fix incorrect image references in `release-4.17`
Please verify and follow up if other places need to be modified as well.
4.18 / master fix: https://github.com/openshift/dpu-operator/pull/126

OCPBUGS-38428: fix image references in 4.17

---

Makefile

With make, when typing `make` without specifying a target, the first target will run. Currently that is `prepare` target which runs `hack/prepare.sh`.
That prepare script, among others, tries to restart libvird service (which requires root). It does not seem something that should be done by default (or regularly).
Instead, the default target should do something that does not require root and is somewhat useful. Doing a local build seems to be that.
Add a "default" target, which is also the first target in the Makefile and thus the default. That invokes the "build" target.
This makes a plain `make` doing something more(?) useful.

[th/makefile-default] Makefile: add default target that does a local build

---

Makefile

It is currently not working yet. Disable it for now, otherwise the "e2e-test" target will fail.
Note that currently there is a bug in "deploy_tft_tests" target, so currently it is also not called. So this change has little effect. However, it will have effect, when that bug is fixed (and the target starts to fail for real).

[th/disable-tft-tests] Makefile: disable "deploy_tft_tests" step from "e2e-test" for now

---

cmd/daemon/daemon.go
cmd/main.go
config/dev/local-images-template.yaml
internal/controller/bindata/daemon/99.daemonset.yaml
internal/controller/dpuoperatorconfig_controller_test.go
internal/daemon/plugin/bindata/vsp-ds/99.vendor-plugin-daemonset.yaml
internal/daemon/plugin/vendorplugin.go
internal/platform/ipu.go
internal/platform/marvell-dpu.go
internal/platform/platform.go
pkgs/render/render.go

With #128 merged, there is now a way for starting the VSP plugin from the operator.
However, there are various missing pieces.
Fix some of the issues, in particular to fix starting the Marvell VSP in the DPU.
CC: @bbhamidipati , @alkamah-marvell , @hasan-alkama (FYI)

[th/vendor-plugin-deploy] various fixes for starting the Marvell VSP on the DPU

---

internal/daemon/dpudaemon.go
internal/daemon/hostdaemon.go
internal/daemon/plugin/vendorplugin.go
internal/platform/ipu.go
internal/platform/marvell-dpu.go

daemon: Crash if vsp init fails
In the case that the vsp is not able to be started, the daemon should
crash and retry.
Currently there is a race condition when deploying the vsp from the
operator where the vsp may fail to come up by the time "start" is
called. This patch should address this race by retrying the daemon pod
deployment.
It makes sense to crash anyways, since the daemon on its own is useless
without a running vsp, and we want to be able to easily see that an
error has occured (i.e. daemon ends up in crashLoopBackoff if the vsp is
never deployed).
GrpcPlugin: Don't deploy vsp if image is not set
Make sure we don't deploy vsp in the case WithVspImage is called with an
empty vsp string.
plugin: Use string constants for VSP image names

Fix vsp deploy

---

Makefile
hack/deploy_traffic_flow_tests.sh
hack/ipu_deploy.sh
hack/ipu_host_deploy.sh
hack/prepare.sh

Since prepare might be ran on a different system to init the module, we don't want to start libvirtd. That logic should be part of cda. In addition, don't mix the venv of the two submodules.

E2e cleanup

---

bundle/manifests/dpu-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/dpuoperatorconfig_controller.go
manifests/stable/dpu-operator.clusterserviceversion.yaml

When bumping the daemon permissions to reconcile the service function
chain, we did not also bump these permissions on the manager.
As a result the controller has been silently failing to deploy the
daemon

Fix failing daemon deployment

---

internal/daemon/device-plugin/deviceplugin.go
internal/daemon/dpudaemon.go
internal/daemon/hostdaemon.go

- Errors were not handled properly in the dpu device plugin
- When an error occurred, it wasn't clear from the test output where the error came from
- 8080 is used frequently. For that reason, change the metrics server port

Fix race + improve error logging + use less common port 

---

Makefile
hack/deploy_fast.sh
hack/deploy_traffic_flow_tests.sh
hack/ipu_deploy.sh
hack/ipu_deploy_post.sh
hack/ipu_host_deploy.sh
hack/ipu_host_deploy_post.sh
hack/prepare-venv.sh

- hack: make scripts executable and add shebang
- hack: use "set -e" to fail scripts on error
- Makefile: directly call scripts instead of using variables

[th/hack-scripts-cleanup] cleanup hack scripts

---

Makefile
scripts/check-gittree-for-diff.sh

We have multiple go.mod files, this does not seem to agree with operator-sdk. operator-sdk will generate files and call `make generate`. However, that will then fail because we didn't call `go mod tidy` for api/ directory.
Note that compared to sriov-network-operator, in dpu-operator we have several go.mod files. That does not seem to agree with operator-sdk, or at least, something is not hooked up right.
Hack `make generate` to call `go mod tidy` first.
Otherwise:
```
$ git checkout -B C origin/main && \
git reset --hard HEAD && \
git clean -fdx && \
make operator-sdk && \
./bin/operator-sdk create webhook --group config --version v1 --kind DpuOperatorConfig --defaulting --programmatic-validation
branch 'C' set up to track 'origin/main'.
Reset branch 'C'
Your branch is up to date with …
```

[th/make-generate-tidy] makefile: run `go mod tidy` during `make generate`

---

hack/cluster-configs/config-dpu-host.yaml
hack/cluster-configs/config-dpu.yaml

Ensure that we only rebuild the images once per CI run. Include a bump to CDA to ensure the correct images are available when testing.

hack: Be explicit with image rebuild behavior

---

hack/cluster-configs/config-dpu-host.yaml
hack/cluster-configs/config-dpu.yaml

This commit introduces intel/ipu-opi-plugins@81c6a0e to remove the race condition between the vsp and p4 pod initializing.
We also remove the corresponding workaround in the automation script to wait for the p4 to finish initializing before proceeding.

[IIC-425] Remove race condition between pod/vsp

---

hack/cluster-configs/config-dpu-host.yaml
hack/cluster-configs/config-dpu.yaml

We should no longer need to hack a script to ensure primary networking is working at all times. This should be handled by the VSP now.

[IIC-427] Remove need to run ipu_port1 manually

---

Makefile

"/root/config.json" is only accessible to root, which means it makes the build not usable to regular users. That is bad.
Instead, if the build will require a login, then require the caller to first issue a suitable `podman login registry.ci.openshift.org` or configure podman in a similar way, so that a subsequent pull works.  If the user prefers to use files, they still can put the auth file to the well known place, but that place is "/run/user/$UID/containers/auth.json" or "~/.config/containers/auth.json", not "/root/config.json".
That is essentially the same as before: the caller must prepare the system in a way so that pull is gonna work. Except, now they have all the options that podman (e.g. `podman login`) offers, instead of hard coding some file at "/root/config.json".
You can …

[th/buildah-no-authfile] build: don't use `--authfile /root/config.json` for buildah commands

---

Makefile
hack/cluster-configs/config-dpu-host.yaml

Rename ocpcluster masters

---

hack/cluster-configs/config-dpu-host.yaml

With this change, the "network_api_port" comes from the google spread sheet. This makes the config also work on the Marvell clusters 15 and 16 which happen to use "eno1" interface (as indicated in the spread sheet).
---
Spin-off from #255 .

[th/cluster-config-network-api-port] cluster-configs: set "network_api_port" from ANL lab list

---

internal/daemon/plugin/bindata/vsp-ds/99.vendor-plugin-daemonset.yaml
internal/daemon/vendor-specific-plugins/marvell/main.go

This is a re-creation of https://github.com/openshift/dpu-operator/pull/262
The patches are the same. This is a continuation of 262, and only exists to workaround a glitch in CI.
Consider it the same PR, and continue discussion here.

[th/mrvl-enable-ipv6-link-local] [V2] rework configuring IPv6 link local addresses for Marvell VSP

---

internal/daemon/vendor-specific-plugins/marvell/00.daemonset.yaml
internal/daemon/vendor-specific-plugins/marvell/debug-dp/debugdp.go
internal/daemon/vendor-specific-plugins/marvell/main.go
internal/daemon/vendor-specific-plugins/marvell/mrvl-utils/mrvlutils.go
internal/daemon/vendor-specific-plugins/marvell/ovs-dp/ovsdp.go

This Commits adds CreateBridgePort() and DeleteBridgePort() API Support
for Marvell VSP Additionally, it integrates the OVS with netdev or DPDK data plane
and  debug data plane functionality for better debugging  within Marvell VSP

Add CBP(),DBP()  to Marvell VSP

---

hack/both.sh
hack/deploy_traffic_flow_tests.sh
hack/ipu_deploy.sh
hack/ipu_deploy_post.sh
hack/ipu_host_deploy.sh
hack/ipu_host_deploy_post.sh
hack/prepare-venv.sh

Some minor cleanup.
- hack: drop unnecessary "python3.11 -m venv /tmp/cda-venv"
- hack: call ./cda.py directly without explicit python interpreter
- hack: don't call versioned pip/python binaries

[th/hack-scripts-cleanup] cleanup hack scripts w.r.t. python and venv

---

hack/cluster-configs/config-dpu.yaml

In CDA, internally the bmc.user already defaults to "root". So setting this had no real effect. Using "root" is suitable for the IPU clusters that we have.
Btw, note that CDA's ipu.IPUBMC() also can hack certain passwords to another hard coded value. So it's not the case that CDA always honors the settings from the cluster config yaml.
The problem is that we want that this same config also works against Marvell DPUs. In such clusters, the "BMC" is the x86_64 host that contains the DPU. We usually expect that host to be an OCP node and run CoreOS. As such, we assume that we can ssh into the host using "core" user and public key authentication.
Note that currently the bmc.user cannot be templated from the google spreadsheet. To make "hack/cluster-configs/config-dpu.yaml" work with Marvell …

[th/marvell-bmc-user] cluster-configs: remove the bmc.user from "config-dpu.yaml" (2)

---

hack/cluster-configs/config-dpu.yaml

We want to use "hack/cluster-configs/config-dpu.yaml" to deploy also
our Marvell DPUs.
In our clusters, we will need "network_api_port" set to "eno2" instead
of "eno12409".
Get the value from the cluster info in the Google spread sheet.

[th/cluster-config-network-port] cluster-configs: set "network_api_port" for ISO clusters from cluster info

---

e2e_test/e2e_test.go
internal/controller/bindata/daemon/04.daemon_cluster_role.yaml
internal/controller/bindata/daemon/99.daemonset.yaml
internal/controller/dpuoperatorconfig_controller.go
internal/controller/dpuoperatorconfig_controller_test.go
internal/daemon/daemon.go
internal/daemon/dpusidemanager.go
internal/daemon/dpusidemanager_test.go
internal/daemon/hostsidemanager.go
internal/daemon/plugin/vendorplugin.go
internal/daemon/sfc-reconciler/sfc.go
internal/platform/ipu.go
internal/platform/marvell-dpu.go
internal/platform/platform.go
internal/scheme/scheme.go
internal/testutils/kindcluster.go
pkgs/vars/vars.go

Set vsp owner reference to dpuOperatorConfig
We want the vsp daemonset to be owned by some resource such that the vsp will be garbage collected properly.
Ideally this would be the daemon or dpu-daemon daemonset, but kubernetes does not allow pods or daemonsets to own other controllers.
A good step in the right direction is to have the vsp owned by the same custom resource that owns the dpu daemon.
A potenital next step might be to add an additional manager for coordinating deployment of the vsp.

Set Owner Reference in VSP

---

Dockerfile.IntelVSP.rhel
Dockerfile.daemon.rhel
Dockerfile.mrvlVSP.rhel
Dockerfile.rhel

There is an issue that causes go multiarch to hang indefinitely sometimes [1].
Per the comments on the issue, it seems setting GOMAXPROCS to a small number can relieve this issue as a temporary workaround
[1] https://github.com/golang/go/issues/70329

Add gomaxproc when building

---

hack/traffic_flow_tests.sh

- hack: adjust detection of acc node for "traffic_flow_tests.sh"
- hack: enable debug logging when running "tft.py" tests

[th/tft-fixes] fix traffic-flow-tests for marvell cluster and enable debug logging

---

hack/traffic_flow_tests.sh

On Jenkins, the workspace gets wiped on each run, so the "ft-logs" directory is empty and there is no problem.
However, it's also useful to manually access the cluster and run `make traffic-flow-tests` (or a full `make e2e-test`). In that case, the result files pile up and "ft-logs/*.json" also evaluates past result files.
Fix that by using the "--output-base" parameter, which exists for this case.

[th/tft-output] tft: fix script to only evaluate latest test run

---

go.mod
go.sum
vendor/github.com/intel/ipu-opi-plugins/ipu-plugin/pkg/ipuplugin/deviceplugin.go
vendor/modules.txt

Intel PR 365: 
Fix for GetDevices, to return PCI address for Host VFs.
Also added caching for GetDevices similar approach like marvell's vsp, so that GetDevices will return total number of Host VFs(and not what is actually available, since that is maintained by DPU code).

Pull Intel PR 365

---

Makefile
e2e_test/e2e_test.go
internal/controller/dpuoperatorconfig_controller_test.go
internal/testutils/testcluster.go
pkgs/drain/drain_test.go
pkgs/vars/vars.go

In order to validate Network Function connectivity, we first need to validate pod-to-pod connectivity.
We will then validate SFC behavior, and validate that pod-to-pod still works once the Network Function has been created
We need to validate that Network Function l3 connectivity is working. Add the tests to validate connectivity both from Network Function to workload pod, and from external client to workload pod.
TODO: Tests assume the external client is the host running e2e-test-suite. It would be nice if an arbitrary client reachable from the DPU could be provided instead.

Extend E2E test suite to validate Network Functions

---

internal/daemon/plugin/bindata/vsp-ds/99.vendor-plugin-daemonset.yaml
internal/daemon/vendor-specific-plugins/marvell/main.go
internal/daemon/vendor-specific-plugins/marvell/mrvl-utils/mrvlutils.go
internal/daemon/vendor-specific-plugins/marvell/ovs-dp/ovsdp.go

Mounted required directories in `vsp.yaml` to enable the default data path as ovs bridge in the Marvell VSP

Marvell: Add support for default data path in VSP

---

Dockerfile.IntelP4.rhel
cmd/intelvsp/p4sdk/entrypoint.sh

Add a dummy Dockerfile to unblock creating the requisite metadata to onboard the p4sdk container with ART

Init Intel p4sdk Dockerfile

---

internal/daemon/plugin/bindata/vsp-ds/99.vendor-plugin-daemonset.yaml

volume "host-libmodules" is not used, and likely it should not be used to not mix core directories of the container with directories from the host. There is already host-root path ("/host") for that.
While at it, add a tailing newline to the file. Text files without trailing newline look odd in editors.

[th/vsp-no-lib-modules] vsp: remove unused volume from "99.vendor-plugin-daemonset.yaml"

---

hack/both.sh
hack/dpu_deploy.sh
hack/dpu_deploy_post.sh
hack/ipu_host_deploy.sh
hack/ipu_host_deploy_post.sh

By default, our cda.py invocations don't enable debug logging. That makes debugging hard.
At least for manual usage, it will be useful if we are able to set `export CDA_OPTIONS='-v debug'` to override that setting.

[th/cda-options] hack: pass $CDA_OPTIONS environment to cda call

---

Makefile

`make redeploy-both` first deploys the operator. At that point, the controller is not yet running and the validating webhook rejects the requests.
```
KUBECONFIG=/root/kubeconfig.microshift oc create -f examples/dpu.yaml
Error from server (InternalError): error when creating "examples/dpu.yaml": Internal error occurred: failed calling webhook "vdpuoperatorconfig.kb.io": failed to call webhook: Post "https://dpu-operator-webhook-service.openshift-dpu-operator.svc:443/validate-config-openshift-io-v1-dpuoperatorconfig?timeout=10s": no endpoints available for service "dpu-operator-webhook-service"
make: *** [Makefile:126: redeploy-both] Error 1
```
Add a `oc wait` for the controller pod to be ready.

[th/make-redeploy-wait] build: wait during redeploy-both before creating DpuOperatorConfig

---

hack/prepare-venv.sh

We have broken "/tmp/tft-venv" environments. It's not clear how that can happen, maybe "prepare-venv.sh" runs in parallel (unlikely as it seems).
Note that setting up a python venv cannot be done concurrently.
Avoid that potential problem by adding a file lock and see whether that avoids the corruption.

[th/prepare-venv-flock] prepare-venv: add file locking to avoid concurrent run

---

hack/prepare-venv.sh

We sometimes seem to end up with a broken venv in /tmp/tft-venv.
```
Error processing line 1 of /tmp/tft-venv/lib64/python3.11/site-packages/distutils-precedence.pth:
Traceback (most recent call last):
File "<frozen site>", line 195, in addpackage
File "<string>", line 1, in <module>
AttributeError: module '_distutils_hack' has no attribute 'add_shim'
```
It's still not clear why this happens, but it might be related to old pip/setuptools version. Update them in the hope to resolve this issue.
---
See for example https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_dpu-operator/382/pull-ci-openshift-dpu-operator-main-make-e2e-test/1925168886706081792

[th/tft-venv-update] hack: upgrade pip modules for tft-venv

---

e2e_test/e2e_test.go

Marvell does not yet pass this test. The caller (Jenkins) will set SKIP_NF_TESTING=1 when running on Marvell, to get a pass on the overall suite -- with the exeception of the tests that are known to fail and which are opted out via SKIP_NF_TESTING.

[th/e2e-test-skip-nf] e2e_test: skip pod2pod test with NF for SKIP_NF_TESTING=1

---

e2e_test/e2e_test.go
internal/testutils/testcluster.go

We're hitting a flake where the pod is not coming up on time during SFC creation. This PR improves the logging around the whole creation process by splitting it up in 2 Eventually blocks. First, the pod needs to be created. Next, it should eventually be in running state. If it's not, we need to know what state it is in do help debug this.

Improve log message on why test failed

---

cmd/daemon/daemon.go
internal/daemon/daemon.go
internal/daemon/daemon_test.go
internal/daemon/plugin/vendorplugin.go

- Run the side manager in a go routine. Final preparation PR for DPU CR.
- Avoid a spurious restart of dpu daemon as it tries to connect to vsp that's not up yet by retrying for 10 seconds.

Dectection loop and handle racy starts

---

taskfiles/clusters.yaml

With [1], we no longer need to set the environment variable. Drop this.
[1] https://github.com/bn222/cluster-deployment-automation/pull/355

taskfiles: drop workaround for deploying marvell

---

openshift/install-dpu.sh
openshift/requirements-build.txt

`dpu-intel-ipu-vsp` is failing to build in Brew on aarch64 due to 2 issues:
- missing `cython` dependepcy 
- running out of memory while building wheel for `grpcio` package. grpcio by default uses all available CPUs for parallel compilation and Brew's aarch64 machines have 3 times more CPUs than the other machines, causing OOM errors.
This PR pins `cython` to 3.0.0 and limits the number of compiler jobs of grpcio build
Test build of this PR: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=68166504

OCPBUGS-58423: Fix Brew build issues for dpu-intel-ipu-vsp

---

go.mod
go.sum
vendor/github.com/intel/ipu-opi-plugins/ipu-plugin/pkg/ipuplugin/lifecycleservice.go
vendor/github.com/intel/ipu-opi-plugins/ipu-plugin/pkg/p4rtclient/p4rtclient.go
vendor/github.com/intel/ipu-opi-plugins/ipu-plugin/pkg/utils/utils.go
vendor/modules.txt

This version addresses slow progression of Host and IPU pod creation/deletion flow due to extended delays in P4 rule updates at IPU.
We now derive the VSI and vPort directly from the VF’s MAC address. Previously, we queried the IMC in real time during P4 rule programming, which added latency to rule add/delete APIs and slowed NF and host pod provisioning.
This update eliminates those frequent IMC calls for VFs, while we continue to query IMC for PHY interfaces (primary/secondary networks) since their MACs can be statically configured via NVMe.
Refer IIC-641 for more context.

IPU plugin version update

---

internal/daemon/vendor-specific-plugins/common/vspnetutils.go
internal/daemon/vendor-specific-plugins/intel-netsec/main.go

- This commit makes sure that spoof check is turned off and trust is turned on for the SR-IOV interfaces
- Then it takes those SR-IOV interfaces and plumbs it into an OvS bridge
- In order to plumb the correct interface, the VSP needs to convert the OPI API bridge port name to PF/VF indexes.
Additionally log levels were reduced down to prevent flooding of logs.
Also workaround issue with e810/e823 interfaces are not VLAN aware. Intel NetSec Accelerator e810 interfaces are not VLAN-aware in VEB mode, thus packets can be forwarded to MAC addresses across VLAN boundaries. This violates the IEEE802.1Q forwarding rules.
This issue is tracked here: https://issues.redhat.com/browse/RHEL-104927
To workaround this we need to set the host side to vepa mode. This would bypass the loopback on the …

Add OvS Support for the PTL

---

config/manager/manager.yaml
internal/controller/dpuoperatorconfig_controller.go
internal/utils/filesystem_mode_detector.go
internal/utils/filesystem_mode_detector_test.go
internal/utils/path_manager.go
internal/utils/suite_test.go

The reason why we had the flavours as Openshift vs Microshift is that we assumed that if the DPU Operator is running on Openshift then it runs an immutable operating system, which in this case is CoreOS. Like wise if the operator is running on Microshift we assumed that the node is running classic RHEL (mutable). The assumptions are not wrong in our previous use cases but microshift's target audience seems to be for immutable flavors of RHEL, so we should make this more robust by checking whether a system is Classic RHEL or if its an OSTREE-Based RHEL, since it gives us a better way to know if parts of the filesystem is writeble or if binaries can even be installed on it by the Operator. This would also add compatibility with running Microshift on RHEL Image Mode, RHEL for edge or RHEL …

feat: Change the flavour focus away from microshift vs openshift

---

bundle/manifests/dpu-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/bindata/daemon/04.daemon_cluster_role.yaml
internal/controller/dpuoperatorconfig_controller.go
manifests/stable/dpu-operator.clusterserviceversion.yaml

`oc logs pod/dpu-operator-controller-manager-6f6cdb4f8f-m58g9` is full of
E0812 16:15:22.598795       1 reflector.go:166] "Unhandled Error" err="sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go:108: Failed to watch *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:openshift-dpu-operator:dpu-operator-controller-manager\" cannot watch resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" logger="UnhandledError"

[th/rbac-watch-crd] give RBAC permission to watch CRD

---

Dockerfile.daemon.rhel
internal/controller/bindata/daemon/99.daemonset.yaml
internal/daemon/daemon.go
internal/daemon/daemon_test.go
internal/daemon/dpusidemanager.go
internal/daemon/dpusidemanager_test.go
internal/daemon/hostsidemanager.go
internal/daemon/hostsidemanager_test.go
internal/daemon/plugin/vendorplugin.go
internal/daemon/vendor-specific-plugins/common/vspnetutils.go
internal/daemon/vendor-specific-plugins/intel-netsec/main.go
internal/platform/ipu.go
internal/platform/marvell-dpu.go
internal/platform/platform.go
internal/platform/vendordetector.go

This commit makes the final adjustments needed for the in-memory DPU list to be represented as Kubernetes Custom Resources (CRs). The changes are as follows:
* **Fixed a context-based side manager race:** A previous 10-second timeout was too short for the VSP to start, so the connection logic now blocks forever until the connection is established. The next PR will report the DPU CR as `NotReady` until the connection is fully established.
* **Added initial multi-DPU support:** The code is being prepared for future support of multiple DPUs, even though VSPs don't support it yet. For now, it will error out if more than one DPU is detected.
* **Refactored manager completion logic:** The logic for handling manager completion was refactored. The `done` variable is now passed directly to the …

Detect DPUs and represent them in memory

---

examples/my-pod.yaml
internal/daemon/sfc-reconciler/sfc.go

* Grant privileged access to SFC container
* Remove AllowPrivilegeEscalation since privileged automatically makes it true
* Correct typo in my-pod.yaml for privileged
Signed-off-by: Sayan Bandyopadhyay <sayan.bandyopadhyay@intel.com>
(cherry picked from commit 13b0558d64934eeabbf7488ce937376147adb4ca)
Without this, we don't have permissions to run the default "nginx" container. While we may revise this in the future, this is what we currently do on main branch. Backport.

OCPBUGS-60658: [th/priviledged-sfc] Make the SFC container to be in privileged mode

---

api/v1/dpuoperatorconfig_types.go
api/v1/dpuoperatorconfig_webhook.go
api/v1/dpuoperatorconfig_webhook_test.go
config/crd/bases/config.openshift.io_dpuoperatorconfigs.yaml
config/samples/config_v1_dpuoperatorconfig.yaml
e2e_test/e2e_test.go
examples/dpu.yaml
examples/host.yaml
examples/my-pod-2.yaml
internal/controller/dpuoperatorconfig_controller.go
internal/controller/dpuoperatorconfig_controller_test.go
internal/daemon/daemon_test.go
internal/daemon/vendor-specific-plugins/common/vspnetutils.go
internal/daemon/vendor-specific-plugins/intel-netsec/main.go
internal/testutils/testcluster.go
vendor/github.com/openshift/dpu-operator/api/v1/dpuoperatorconfig_types.go
vendor/github.com/openshift/dpu-operator/api/v1/dpuoperatorconfig_webhook.go

Remove Mode field for proper "auto" support
-  Remove the Mode field in the DPU Operator Config CRD because it is no longer needed when we auto detect whether each node is running with vs. on a DPU. This auto detection was completed in prior commits.
-  Remove all references to the Mode field in tests and code
- When creating NADs, we create both NADs for host and DPU
- This does not break existing setups since the auto detection code is in and the mode field is only used to control the creation of NADs.
Add support for Layer 3 Network Functions
- Revised VethPairs data structure to handle lookups by MAC address. This is needed since the API for creating network functions is by MAC address of the veth interface.
- To support Layer 3 Network Functions, the veth ports are simply connected …

Remove Mode field and Add support for Layer 3 Network Functions on PTL

---

config/crd/bases/config.openshift.io_dataprocessingunits.yaml
config/crd/bases/config.openshift.io_dpuoperatorconfigs.yaml
config/crd/bases/config.openshift.io_servicefunctionchains.yaml
config/rbac/role.yaml
taskfile.yaml

Recently added prep step to ensure our CI's golang is as new as possible due to other dependencies moving forward. This revealed an issue with the controller-gen that was fixed in a newer version.

Bump controller-gen to fix compatibilty with compiler

---

cmd/daemon/daemon.go
internal/controller/bindata/daemon/99.daemonset.yaml
internal/controller/dpuoperatorconfig_controller.go
internal/controller/dpuoperatorconfig_controller_test.go
internal/daemon/daemon.go
internal/daemon/daemon_test.go
internal/daemon/vendor-specific-plugins/intel-netsec/main.go
internal/daemon/vendor-specific-plugins/marvell/main.go

Packets are generated with the source MAC address of the internal veth interfaces in the network function. Hence we must disable spoof check because the external facing VF is intended to be used like a "switch port" connected to the OvS bridge.
Also remove some lingering auto mode code that can be safely removed.

Spoofchk disable is needed for the external facing VF for PTL

---

Dockerfile.mrvlVSP.rhel
internal/daemon/vendor-specific-plugins/marvell/main.go

As we have veth interfaces, there is no "hardware" to offload to. Instead, we attacht those interfaces to OVS. The veth pair then sends incomplete packets without a checksum, and OVS doesn't fill them in either. The result is a broken checksum and broken TCP.
Fix that by disabling hardware offloading for "tx" and "rx".
https://issues.redhat.com/browse/MDC-122
See-also: https://arthurchiao.art/blog/ovs-deep-dive-5-datapath-tx-offloading/

[th/marvell-veth-no-offload] marvell: disable tx/rx hardware offload on veth pairs

---

e2e_test/e2e_test.go
hack/cluster-configs/config-1-cluster.yaml
hack/cluster-configs/ocp-tft-config.yaml
hack/traffic_flow_tests.sh
internal/testutils/cdacluster.go
internal/testutils/testcluster.go
taskfile.yaml

The current e2e tests assumes 2 clusters. Depending on which kubeconfigs exists we should detect whether it is in 2 cluster or 1 cluster modes. Once the 2 vs 1 cluster deployment is determined, there are code changes to make sure the tests work in either approach.

Refactor 2 cluster in E2E tests and add 1 cluster support

---

taskfile.yaml

All the original tasks are expecting 2 clusters hense using 2 kubeconfigs. However for 1 cluster we need a duplicate set to only look for 1 kubeconfig (OCP).

Add redeploy task for 1 cluster
