openshift/dpu-operator

Makefile, README.md, bindata/daemon/04.daemonset.yaml, config/dev/kustomization.yaml, config/dev/local-images.yaml, config/manager/manager.yaml, internal/controller/dpuoperatorconfig_controller.go
Useful for developing and deploying locally.
=> Add make local-deploy

bindata/sriov-device-plugin/00.sriov-config-map.yaml, bindata/sriov-device-plugin/01.sriov-device-plugin_sa.yaml, bindata/sriov-device-plugin/02.sriov-device-plugin_role.yaml, bindata/sriov-device-plugin/03.sriov-device-plugin_role_binding.yaml, bindata/sriov-device-plugin/04.sriov-device-plugin_ds.yaml, internal/controller/dpuoperatorconfig_controller.go, internal/controller/dpuoperatorconfig_controller_test.go, internal/controller/suite_test.go
Some of the design decisions to add the SR-IOV device plugin daemonset are temporary.
=> Add SR-IOV Device Plugin Support

bindata/daemon/04.daemonset.yaml, daemon/hostdaemon.go, daemon/main.go
sm.CmdAdd has a side effect. It sets fields in its arg.
=> Fix path and move call to sm earlier

bindata/daemon/01.daemon_sa.yaml, bindata/daemon/02.daemon_role.yaml, bindata/daemon/03.daemon_role_binding.yaml, bindata/daemon/04.daemonset.yaml, bundle/manifests/dpu-operator.clusterserviceversion.yaml, config/manager/manager.yaml, internal/controller/dpuoperatorconfig_controller_test.go, manifests/stable/dpu-operator.clusterserviceversion.yaml, manifests/stable/image-references
It should be called DPU Daemon from now on. This is the name that the ART team is expecting.
=> Modify the name of the DPU Operator Daemon

daemon/main.go
This prevents the daemon from erroring out when running on RHCOS (e.g. /opt is not writeable)
=> Add check for writable when copying the CNI

daemon/device-plugin/deviceplugin.go
- Remove use of fmt.Printf
- Simplify ListAndWatch
=> Cleanup Device Plugin Code

api/go.mod, bundle/manifests/dpu-operator.clusterserviceversion.yaml, dpu-api/go.mod, go.mod, manifests/stable/dpu-operator.clusterserviceversion.yaml, vendor/modules.txt
Need new golang version to make gopls work.
=> Bump go version to 1.22.1

Makefile
- This will be used by ci-operator to flag for the need to update "make generate"
=> Add err code for "make generate-check"

Makefile, internal/daemon/dpudaemon_test.go, internal/daemon/hostdaemon_test.go
Expose the `focus` gingko cli arg to allow running part of the tests.
For example:
`make fast-test TEST_FOCUS="Main Controller"`
=> Add optional TEST_FOCUS argument to makefile

internal/daemon/plugin/vendorplugin.go
In the event we cannot establish connection with the vsp via grpc, we should report the error back up to improve debuggability.
=> Return an error if grpc connection to vsp fails

bundle/manifests/dpu-operator.clusterserviceversion.yaml, config/manager/manager.yaml, manifests/stable/dpu-operator.clusterserviceversion.yaml
Successfully created task: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=63418243
=> OCPBUGS-38580: [4.17] Bump manifests to 4.17

internal/testutils/test_cluster.go
`make test` sometimes fails for me. Increase the timeout at one place and add a retry at another.
=> [th/test-increase-timeouts] increase timeout and retry against random failures of `make test`

Dockerfile.mrvlVSP.rhel, internal/daemon/vendor-specific-plugins/marvell/main.go
This commit adds GetDevice Support for mrvl-vsp
=> Add GetDevice() to Marvell VSP

cmd/daemon/daemon.go, examples/my-pod.yaml, hack/cluster-configs/config-dpu-host.yaml, hack/cluster-configs/config-dpu.yaml, internal/controller/bindata/daemon/04.daemon_cluster_role.yaml, internal/daemon/daemon.go, internal/daemon/dpusidemanager.go, internal/daemon/hostsidemanager.go
=> Get closer to green ci

hack/cluster-configs/config-dpu-host.yaml, hack/cluster-configs/config-dpu.yaml
Up till now we have validated "kubecon" branch is working. We now need to move to the merge with main to validate recent updates.
=> hack: Bump vsp to main branch

.dockerignore, hack/cluster-configs/config-dpu-host.yaml, hack/cluster-configs/config-dpu.yaml
If this passes,then I will merge all changes in CDA too to simplify deployment process.
=> Bump again

Dockerfile.CNI.rhel, Dockerfile.IntelVSP.rhel, Dockerfile.daemon.rhel, Dockerfile.mrvlVSP.rhel, Dockerfile.rhel, Makefile, bundle/manifests/dpu-operator.clusterserviceversion.yaml, config/manager/manager.yaml, manifests/dpu-operator.package.yaml, manifests/stable/dpu-operator.clusterserviceversion.yaml, manifests/stable/image-references
This should now work after the introduction of proper cross-compilation
=> OCPBUGS-45526,OCPBUGS-45415,OCPBUGS-45375: bump operator version

go.mod, go.sum, vendor/github.com/intel/ipu-opi-plugins/ipu-plugin/ipuplugin/cmd/rootcmd.go, vendor/modules.txt
Pull intel PR 318
https://github.com/intel/ipu-opi-plugins/pull/318
=> Pull intel PR 318

Dockerfile.CNI.rhel, Dockerfile.rhel
@SalDaniele quick fix for slow builds I came across while I'm adding incremental builds
=> remove -a from build

Makefile, cmd/daemon/daemon.go, cmd/main.go, e2e_test/e2e_test.go, hack/cluster-configs/ocp-tft-config.yaml, hack/deploy_traffic_flow_tests.sh, internal/controller/dpuoperatorconfig_controller_test.go, internal/daemon/daemon.go, internal/daemon/dpusidemanager.go, internal/daemon/hostsidemanager.go, internal/scheme/scheme.go
Cleanup and refactor in prep for dpu CR
=> Bn refactor

Makefile
- Makefile: fix steps in local-buildx-incremental-intel-vsp target
- Makefile: fix incremental-local-buildx target
=> [th/makefile-fixes] some fixes to Makefile related to incremental-local-build

internal/daemon/vendor-specific-plugins/marvell/main.go
This Commits replaces generated IPv6 address with static one for the link local 
comm channel between host and dpu.
Signed-off-by: Alkama Hasan <alkamah@marvell.com>
=>     IPv6 link local rework  to Marvell VSP

cmd/daemon/daemon.go, go.mod, internal/daemon/daemon.go, internal/utils/cluster_environment.go, internal/utils/fileutils.go, internal/utils/path_manager.go
Add part of the infrastructure needed to allow testing the daemon level code against a kind cluster.
=> Add afero and allow daemon to run against Kind cluster

internal/daemon/vendor-specific-plugins/marvell/main.go
When adding IPv6 addresses, they are for a short time in tentative state while doing DAD. At that time, the address is not yet usable.
This causes failures:
```
Daemon  Failed to listen        {"error": "Failed to start listening on [fe80::1%enP2p1s0v0]:8085: listen tcp [fe80::1%enP2p1s0v0]:8085: bind: cannot assign requested address"}
```
Make the address optimistically available.
=> [th/mrvl-optimistic-ipaddr] marvell: configure IPv6 addresses with optimistic DAD

internal/daemon/vendor-specific-plugins/marvell/ovs-dp/ovsdp.go
Ensure the interface is set up when we add it to the bridge.
---
CC: @alkama-hasan
=> [th/mrvl-set-if-up] marvell: set interface up when adding port bridge

internal/daemon/vendor-specific-plugins/marvell/main.go
This should should be idempotent and accept that the interface might already exist. Especially, since createVethPair() can be called multiple times.
```
I0214 10:43:39.226702       1 main.go:218] Received Init() request: DpuMode: true
...
I0214 10:43:39.542460       1 main.go:161] Creating Veth Pairs: 2
...
I0214 10:44:06.202503       1 main.go:218] Received Init() request: DpuMode: true
...
I0214 10:44:06.517237       1 main.go:161] Creating Veth Pairs: 2
E0214 10:44:06.517348       1 main.go:165] Error occurred in creating Veth Pair: file exists
I0214 10:44:06.719772       1 main.go:147] Deleted Veth Pair: nf_interface0
I0214 10:44:06.919443       1 main.go:147] Deleted Veth Pair: nf_interface1
E0214 10:44:06.919460       1 main.go:227] Error occurred in configuring Network Interface: …
```
=> [th/mrvl-create-veth-pair-once] marvell: accept existing interface in createVethPair()

go.mod, go.sum, vendor/github.com/intel/ipu-opi-plugins/ipu-plugin/pkg/p4rtclient/p4rtclient.go, vendor/github.com/intel/ipu-opi-plugins/ipu-plugin/pkg/p4rtclient/rh_p4client.go, vendor/github.com/intel/ipu-opi-plugins/ipu-plugin/pkg/utils/utils.go, vendor/golang.org/x/crypto/ssh/handshake.go, vendor/golang.org/x/net/context/context.go, vendor/golang.org/x/net/context/go17.go, vendor/golang.org/x/net/context/go19.go, vendor/golang.org/x/net/context/pre_go17.go, vendor/golang.org/x/net/context/pre_go19.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/transport.go, vendor/golang.org/x/net/internal/httpcommon/headermap.go, vendor/golang.org/x/net/internal/httpcommon/request.go, vendor/golang.org/x/net/proxy/per_host.go, vendor/modules.txt
This reverts commit 250008124c4ab5ac95cbb442d78fe024f9222eca, reversing changes made to 3f93fb9dce4e0ae7338b0ba74592f32e255b32af.
=> Revert "Merge pull request #339 from saynb/flow_test_fail"

Makefile, hack/setup.sh
Preparation for task file based builds
=> Simple deploy

internal/daemon/device-handler/dpu-device-handler/dpudevicehandler.go
Previously the vsp returned getDevices() in an unexpected format (non-pci addresses).
This has since been fixed. We should fail in the event that devices are not provided in this format.
=> IIC-448: Remove workaround for call to GetDevices

internal/daemon/vendor-specific-plugins/marvell/debug-dp/debugdp.go, internal/daemon/vendor-specific-plugins/marvell/main.go, internal/daemon/vendor-specific-plugins/marvell/mrvl-utils/mrvlutils.go, internal/daemon/vendor-specific-plugins/marvell/ovs-dp/ovsdp.go
This commit adds support for CreateNetworkFunction(), DeleteNetworkFunction() API to support traffic flow through NF in Marvell VSP
=> Marvell: Add Support for NetworkFunction in VSP

OWNERS
This PR just adds my user as a reviewer and approver, which should not introduce any breaking changes.
=> OWNERS: Add samd2021 as maintainer 

internal/daemon/dpusidemanager.go
=> Log name change

go.mod, go.sum, vendor/github.com/intel/ipu-opi-plugins/ipu-plugin/pkg/ipuplugin/lifecycleservice.go, vendor/modules.txt
add check for redfish start script
bump go dependencies
=> vendor bump

cmd/daemon/daemon.go, internal/daemon/daemon.go, internal/daemon/daemon_test.go, internal/daemon/dpusidemanager.go, internal/daemon/dpusidemanager_test.go, internal/daemon/hostsidemanager.go, internal/daemon/hostsidemanager_test.go, internal/daemon/plugin/vendorplugin.go, internal/daemon/vendor-specific-plugins/mock-vsp/mockvsp.go
=> Use context.context pattern

hack/prepare-venv.sh
ktoolbox is usually
https://raw.githubusercontent.com/thom311/ktoolbox/85ed9ba7ff346f20a02c78beffba9df08c67729a/wheels/155.6601dd6cdf03/ktoolbox-0.8.0-py3-none-any.whl
or it could be
git+https://github.com/thom311/ktoolbox@6601dd6cdf031f2f0daeb6ebe333cd6e0740e83a
This requires special handling. Unfortunately, we cannot in general know the resulting pip package for a certain package URL (for example, pip packages can contain hyphens, so we cannot just strip them in general). Instead, we need to special case ktoolbox.
Otherwise, the venv always appears broken, and we re-create it. Actually twice during one `task e2e-test` run.
=> [th/fix-prepare-venv] prepare-venv: fix checking for valid ktoolbox package in venv

examples/my-pod.yaml, internal/daemon/sfc-reconciler/sfc.go
Correcting typo in my-pod.yaml
=> Making the SFC container to be in privileged mode

api/v1/dataprocessingunit_types.go, cmd/daemon/daemon.go, config/crd/bases/config.openshift.io_dataprocessingunits.yaml, internal/daemon/daemon.go, internal/daemon/daemon_test.go, internal/platform/vendordetector.go, vendor/github.com/openshift/dpu-operator/api/v1/dataprocessingunit_types.go
report what node the DPU is on
=> Add node name into DPU CR

README.md, examples/sfc-pod.yaml
Additionally added an example sfc-pod yaml. This currently works on the Intel NetSec Accelerator in a one cluster deployment.
=> Update README with one cluster deployment
